### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.website#18]
So the title is pretty self-explaining. If approved I can add it myself.

**Comment by danielpeintner** [comment]
I did have a local .gitignore but forgot to check it in.
In the meanwhile I did so with my local requirements, see https://github.com/eclipse/thingweb.website/commit/d7106e3ca46d52354a14f90cbdf72a3ad7bf7479

Do you need more ignores?

**Comment by fatadel** [comment]
@danielpeintner I would also add `.vscode`

**Comment by danielpeintner** [comment]
Did so, see https://github.com/eclipse/thingweb.website/commit/58add5e8c61e3331c9312ef1f6575ad7ed9108d0

**Comment by fatadel** [comment]
Thank you, @danielpeintner!

**Comment by fatadel** [comment]
I would remove `!.vscode/settings.json` from `.gitignore`.
I think there are more cases when we don't want to exchange this file rather than cases when we want.
For example, the spell checker extension I use adds ignored words to that file. I suppose they shouldn't be in the repo.

**Comment by fatadel** [comment]
I would remove `!.vscode/settings.json` from `.gitignore`.
I think there are more cases when we don't want to exchange this file rather than cases when we want.
For example, the spell checker extension I use adds ignored words to that file. I suppose they shouldn't be in the repo.

**Comment by danielpeintner** [comment]
You might be right, let's *ignore* all files vscode files (see https://github.com/eclipse/thingweb.website/commit/c066f89d36ef292575be12575839f6cea42635d2)
