### ISSUE TITLE
Thingweb vserver moved

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.website#35]
see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1129

I did a quick check and it seems to work fine.

@sebastiankb @egekorkan @wiresio @relu91 please let me know if you encounter any issues

**Comment by egekorkan** [comment]
I can still ssh with the same credentials as before :partying_face:

**Comment by danielpeintner** [comment]
No issues detected by now -> closing
